r2013-02-18-tunr/config/routes.rb
R20130218Tunr::Application.routes.draw do

  root :to => 'home#index'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  resources :users, :except => [:edit] do
    collection do
      get 'edit'
    end
  end

  resources :genres, :albums, :artists, :mixtapes

  resources :songs do
    member do
      get 'purchase'
      post 'buy'
    end
  end

end

r2013-02-18-tunr/app/models/song.rb
# == Schema Information
#
# Table name: songs
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  image      :string(255)
#  filename   :string(255)
#  artist_id  :integer
#  album_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  cost       :decimal(, )      default(1.0)
#

class Song < ActiveRecord::Base
  attr_accessible :name, :image, :filename, :artist_id, :album_id, :cost, :genre_ids, :mixtape_ids
  belongs_to :artist, :inverse_of => :songs
  belongs_to :album, :inverse_of => :songs
  has_and_belongs_to_many :mixtapes
  has_and_belongs_to_many :genres
  validates :cost, :numericality => { :greater_than => 0 }
  validates :name, :uniqueness => true, :presence => true
end

r2013-02-18-tunr/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  image           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#  is_admin        :boolean          default(FALSE)
#  balance         :decimal(, )      default(0.0)
#

class User < ActiveRecord::Base
  has_secure_password
  attr_accessible :name, :image, :password, :password_confirmation, :is_admin, :balance
  has_many :mixtapes
  has_and_belongs_to_many :albums
  validates :image, :presence => true
  validates :name, :uniqueness => true, :length => { :minimum => 2 }
  validates :balance, :numericality => { :greater_than_or_equal_to => 0 }
end

r2013-02-18-tunr/app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_filter :check_if_admin, :except => [:index, :show, :purchase, :buy]

  def index
    @songs = Song.all
  end
  def new
    @song = Song.new
  end
  def create
    @song = Song.new(params[:song])
    if @song.save
      redirect_to(songs_path)
    else
      render :new
    end
  end
  def edit
    @song = Song.find(params[:id])
    @user = @auth
    render :new
  end
  def update
    @song = Song.find(params[:id])
    @user = @auth
    if @song.update_attributes(params[:song])
      redirect_to(song_path)
    else
      render :new
    end
  end
  def show
    @song = Song.find(params[:id])
  end
  def destroy
    song = Song.find(params[:id])
    song.delete
    redirect_to(songs_path)
  end
  def purchase
    @song = Song.find(params[:id])
    @user = @auth
  end
  def buy
    @song = Song.find(params[:song_id])
    if @song.update_attributes(params[:song])
      @auth.balance = @auth.balance - @song.cost
      @auth.save
      redirect_to(mixtape_path[:mixtape_id])
    else
      render :purchase
    end
  end
end

r2013-02-18-tunr/app/views/songs/index.html.haml
#songs
  %div= button_to('Add', new_song_path, :method => 'get', :class => 'success button radius') if is_admin
  %h1 Songs
  %table
    %tr
      %th name
      %th image
      %th cost
    - @songs.each do |song|
      - if song.name != nil
        %tr{:class => cycle('row0', 'row1')}
          %td= link_to(song.name, song_path(song))
          %td= image_tag(song.image)
          %td= number_to_currency(song.cost)
          %td= audio_tag(song.filename, :controls => 'true')
          %td= link_to('Edit', edit_song_path(song), :class => 'success button tiny radius') if is_admin
          %td= link_to('Delete', song, :method => 'delete', :class => 'alert button tiny radius') if is_admin

r2013-02-18-tunr/app/views/songs/new.html.haml
.row
  .five.columns
    = render(:partial => '/shared/errors', :locals => {:object => @song})
    = form_for @song do |f|
      = f.label :name
      = f.text_field :name, :autofocus => true
      = f.label :image
      = f.text_field :image
      = f.label :filename
      = f.text_field :filename
      = f.label :cost
      = f.text_field :cost
      - Genre.order(:name).each do |genre|
        %span
          = genre.name
        = check_box_tag("song[genre_ids][]", genre.id, genre.in?(@song.genres.to_a))
      = f.submit nil, :class => 'round button'
  .seven.columns

r2013-02-18-tunr/app/views/songs/purchase.html.haml
%h3= 'Purchase'
%h4= @song.name
%h4= number_to_currency(@song.cost)
%p= image_tag(@song.image)

.row
  .five.columns
    = form_tag buy_song_path do
      =hidden_field_tag('song_id', @song.id)
      -@auth.mixtapes.each do |mixtape|
        %span
          = mixtape.name
        %span
          = check_box_tag("song[mixtape_ids][]", mixtape.id
        - if @auth.balance >= @song.cost
          = submit_tag 'Purchase song', :class => 'round button'
        - else
          = submit_tag 'Purchase song', :class => 'button disabled'
  .seven.columns

r2013-02-18-tunr/app/views/songs/show.html.haml
%h1= @song.name
%p= link_to("#{number_to_currency(@song.cost)}", purchase_song_path(@song.id), :method => 'get', :class => 'success button radius') if @auth.present?

%td= link_to('Edit', edit_song_path(song), :class => 'success button tiny radius') if is_admin

%p= image_tag(@song.image)
%p= audio_tag(@song.filename, :controls => 'true')

%table
  %tr
    %th artist
    %th album
    %tr{:class => cycle('row0', 'row1')}
      %td= @song.artist.name if @song.artist.present?
      %td= @song.album.name if @song.album.present?

%h6= 'Genres'
- @song.genres.each do |genre|
  %p= genre.name